### ISSUE TITLE
zookeeper service load error - Invalid argument

### ISSUE THREAD

**Issue by ghost** [bloomberg/zookeeper-cookbook#6]
I tried this cookbook on centos 7. The service doesn't load. And this is what i see when i run 'systemctl status zookeeper'

```
zookeeper.service - zookeeper
   Loaded: error (Reason: Invalid argument)
```

The systemd  service looks like this

```
[Unit]
Description=zookeeper

[Service]
Environment="JMXPORT=9010" "ZOO_LOG_DIR=/var/log/zookeeper"
ExecStart=bin/zkServer.sh start-foreground /etc/zookeeper/zoo.properties
ExecReload=/bin/kill -HUP $MAINPID
KillSignal=TERM
User=zookeeper
WorkingDirectory=/srv/zookeeper/current/zookeeper-3.5.0-alpha

[Install]
WantedBy=multi-user.target
```

I tried removing the WorkingDirectory and giving the absolute path in ExecStart and tried starting the service. That worked for me.

Am I missing anything here??

**Comment by acaiafa** [comment]
What is your install path?

**Comment by ghost** [comment]
@acaiafa Its the default, which is /srv
So, the entire path '/srv/zookeeper/current/zookeeper-3.5.0-alpha/bin/zkServer.sh' is right.
The problem is really with the way the service is configured using 'WorkingDirectory'.
The moment i remove the WorkingDirectory, add the absolute path in ExecStart and start the service using 'systemctl start zookeeper' it comes up fine.

**Comment by acaiafa** [comment]
@avinashkolluru Ok i am running a test-kitchen on centos and will let you know what i see.

**Comment by acaiafa** [comment]
@avinashkolluru this will fix that issue https://github.com/bloomberg/zookeeper-cookbook/pull/7

**Comment by johnbellone** [comment]
:+1:

**Comment by ghost** [comment]
@acaiafa @johnbellone When will this be available on chef market?
If that is going to take time, is there a work around for me to get this change?

**Comment by acaiafa** [comment]
@avinashkolluru I will check into this in the morning as far as fixing it on the supermarket.

**Comment by johnbellone** [comment]
@acaiafa Once #9 is merged I'll push to supermarket.
